In [2]:
import numpy as np
import time
from BlockSVD import *

In [32]:
A = construct_matrix(m=50000, n=5000, singular_values=\
[1, 0.8, 0.7, 0.5, 0.1, 0.05, 0.01, 0.001, 0.0000001, 0.0000000001])
U_aprx, S_aprx, V_aprx = blockSVD(A, 200, 200, gamma=0.0001)
quality(A, U_aprx, S_aprx, V_aprx)
timeit(np.linalg.svd)(A)

matrix has memory of  1907.3486328125 megabytes
rank of matrix approximation is:  8
execution time: 130.198477268219 seconds
relative error is:  6.464948612601192e-08
np.allclose is:  True
execution time: 0.06563591957092285 seconds


(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([1.05750034e-311, 1.05703884e-311, 0.00000000e+000, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]))

In [48]:
A = construct_matrix(m=5000, n=5000, singular_values=\
[1, 0.8, 0.7, 0.5, 0.1, 0.05, 0.01, 0.001, 0.0000001, 0.0000000001])
timeit(np.linalg.svd)(A)

matrix has memory of  190.73486328125 megabytes
execution time: 33.962015867233276 seconds


(array([[-9.24090431e-03, -2.50988986e-02, -6.43965563e-03, ...,
          1.36885816e-02,  3.23927058e-01,  3.93236063e-01],
        [-5.07874411e-04, -3.55151063e-02, -1.66312645e-02, ...,
          5.05546483e-02, -1.38431660e-01, -1.68188031e-01],
        [-1.50960438e-02,  1.15823112e-02,  1.57942524e-03, ...,
         -5.52658393e-01, -3.06027596e-01,  1.34584733e-02],
        ...,
        [-7.19626422e-03, -2.91187072e-02,  4.34466894e-03, ...,
          6.02471640e-03,  8.65784741e-03, -2.27941668e-03],
        [-5.27311112e-03,  1.88305360e-03, -1.89058058e-02, ...,
         -3.45634983e-03, -7.01261022e-04,  5.42884622e-03],
        [-1.31514741e-02, -2.43342704e-04, -6.22694619e-03, ...,
         -4.98852703e-03,  4.12666065e-03, -6.40577404e-03]]),
 array([1.00000000e+00, 8.00000000e-01, 7.00000000e-01, ...,
        5.25030347e-17, 5.14993022e-17, 1.41370598e-17]),
 array([[-2.07234945e-02, -2.39688366e-02, -8.71496272e-03, ...,
         -2.20021443e-03, -2.22715356e-02, -1

In [49]:
A = construct_matrix(m=10000, n=5000, singular_values=\
[1, 0.8, 0.7, 0.5, 0.1, 0.05, 0.01, 0.001, 0.0000001, 0.0000000001])
timeit(np.linalg.svd)(A)

matrix has memory of  381.4697265625 megabytes
execution time: 66.22969841957092 seconds


(array([[-6.50597557e-03,  1.75499880e-02,  4.60454356e-03, ...,
          8.11940289e-04,  1.50213986e-03,  4.59910655e-05],
        [-3.57564411e-04,  2.48774290e-02,  1.17859844e-02, ...,
          1.26517849e-03, -1.69102776e-04, -1.77010442e-03],
        [-1.06282339e-02, -8.16664270e-03, -1.05266805e-03, ...,
          7.64423467e-04,  1.77741461e-03,  2.34194216e-03],
        ...,
        [-1.56250279e-03,  6.76217251e-04,  2.00169485e-02, ...,
          4.95281576e-01,  4.47028548e-03, -3.77965392e-03],
        [-1.58163386e-02,  4.68113296e-03, -1.29832045e-02, ...,
          2.91871843e-03,  3.94723760e-01,  7.39252807e-03],
        [-1.36173275e-02, -1.18722057e-02,  1.55086879e-02, ...,
         -7.95798023e-04,  2.90996579e-03,  3.85949888e-01]]),
 array([1.00000000e+00, 8.00000000e-01, 7.00000000e-01, ...,
        9.74685144e-17, 7.07838539e-17, 3.52096463e-18]),
 array([[-1.40819131e-02, -2.58378953e-04, -1.88065894e-02, ...,
         -6.58229733e-03, -2.91633142e-03, -1

Experiment start

In [53]:
A = construct_matrix(m=20000, n=5000, singular_values=\
[1, 0.8, 0.7, 0.5, 0.1, 0.05, 0.01, 0.001, 0.0000001, 0.0000000001])
timeit(np.linalg.svd)(A)

matrix has memory of  762.939453125 megabytes
execution time: 137.2986855506897 seconds


(array([[ 4.57287587e-03, -1.24340190e-02, -3.32253237e-03, ...,
          1.12906075e-03,  2.59525508e-04, -2.55907254e-04],
        [ 2.51322442e-04, -1.76624895e-02, -8.37667098e-03, ...,
         -1.80442246e-03,  9.41883414e-04, -1.13950901e-03],
        [ 7.47030077e-03,  5.84305606e-03,  6.87277486e-04, ...,
         -1.09454715e-04,  2.84228510e-04, -3.84961402e-04],
        ...,
        [ 9.91434815e-04, -8.62170340e-03, -1.32464664e-02, ...,
          7.06233610e-01, -3.71717051e-03, -2.00543674e-03],
        [ 7.63907598e-03, -9.88608109e-03, -3.54413868e-03, ...,
         -4.86857665e-03,  7.34837373e-01, -1.28762751e-05],
        [ 1.09926995e-02, -3.13910124e-03,  1.02217770e-02, ...,
         -3.44055582e-03,  3.10274598e-03,  6.41372047e-01]]),
 array([1.00000000e+00, 8.00000000e-01, 7.00000000e-01, ...,
        4.94825388e-17, 4.81965305e-17, 3.54916128e-18]),
 array([[ 6.91378704e-03,  3.51115028e-03,  1.82455811e-02, ...,
          1.44202919e-02,  1.48766215e-02,  1

In [54]:
A = construct_matrix(m=20000, n=5000, singular_values=\
[1, 0.8, 0.7, 0.5, 0.1, 0.05, 0.01, 0.001, 0.0000001, 0.0000000001])
U_aprx, S_aprx, V_aprx = blockSVD(A, 200, 200, gamma=0.0001)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  8
execution time: 49.631569385528564 seconds
relative error is:  6.464948612601911e-08
np.allclose is:  True


Experiment end

In [4]:
A = construct_matrix(m=10000, n=10000, singular_values=\
[1, 0.8, 0.7, 0.5, 0.1, 0.05, 0.01, 0.001, 0.0000001, 0.0000000001])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 1000, gamma=0.0001)
quality(A, U_aprx, S_aprx, V_aprx) 


matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  8
execution time: 49.82099914550781 seconds
relative error is:  6.464948612604958e-08
np.allclose is:  True


In [12]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 1000, gamma=0.0001)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  50
execution time: 75.3153235912323 seconds
relative error is:  2.70859472652553e-15
np.allclose is:  True


In [13]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 1000, gamma=0.1)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  46
execution time: 71.00275611877441 seconds
relative error is:  0.029184005594171746
np.allclose is:  False


In [15]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 1000, gamma=0.5)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  21
execution time: 65.29420185089111 seconds
relative error is:  0.46530928759673046
np.allclose is:  False


In [14]:
timeit(np.linalg.svd)(A)

execution time: 231.5099368095398 seconds


(array([[-0.00645551, -0.01752166,  0.00444191, ...,  0.04414777,
         -0.03483861,  0.01572275],
        [-0.0167116 , -0.00124084,  0.00545271, ..., -0.00140898,
          0.02765656,  0.0063791 ],
        [-0.00054171, -0.01603576,  0.00054633, ..., -0.03157257,
         -0.00855204,  0.01565269],
        ...,
        [-0.00562592, -0.0007968 ,  0.01764564, ..., -0.00398922,
         -0.00319246,  0.00707451],
        [-0.00816887, -0.01350602, -0.01610023, ...,  0.00484463,
         -0.00072118, -0.01800656],
        [-0.01563713,  0.00758123,  0.01065396, ..., -0.00256852,
          0.00769256, -0.00239902]]),
 array([9.84533274e-01, 8.96570411e-01, 8.93943542e-01, ...,
        1.69151984e-17, 1.49698212e-17, 5.79307360e-18]),
 array([[-5.19052662e-03, -1.60355643e-02, -1.02935599e-02, ...,
         -1.34664824e-02, -5.03943241e-03, -1.55933196e-02],
        [ 7.51084571e-03, -8.28092562e-03,  6.34353432e-03, ...,
         -1.26847763e-02,  1.31221422e-02,  1.50143180e-03],
  

In [25]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.pareto(5, 50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 1000, gamma=0.0001)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  50
execution time: 69.13762140274048 seconds
relative error is:  2.80186809997225e-15
np.allclose is:  True


In [26]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.pareto(5, 50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 1000, gamma=0.1)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  28
execution time: 63.27093744277954 seconds
relative error is:  0.13678694039493008
np.allclose is:  False


In [27]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.pareto(5, 50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 1000, gamma=0.05)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  36
execution time: 65.5826427936554 seconds
relative error is:  0.0760187324143413
np.allclose is:  False


внизу считалось ужасно долго (~20 мин)

In [28]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10, 10, gamma=0.5)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes


KeyboardInterrupt: 

Do column-wise and row-wise partitions and see column-wise partitions are better

In [29]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 100, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 118.20474767684937 seconds
relative error is:  0.001292946826372431
np.allclose is:  False


In [30]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 100, 10000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 162.28913593292236 seconds
relative error is:  0.0012929468264108344
np.allclose is:  False


proceed with column-wise partition + row-wise partition of size 2

In [32]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 5000, 100, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 88.3730628490448 seconds
relative error is:  0.0012929468266200976
np.allclose is:  False


делим строку еще по 2.

In [33]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 2500, 100, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 93.86327385902405 seconds
relative error is:  0.001292946826450673
np.allclose is:  False


 делим строку еще по 2.

In [34]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1250, 100, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 133.7633466720581 seconds
relative error is:  0.0012929468261506213
np.allclose is:  False


дальше хуже

попробуем по колонкам только поделить, но сделать 500 вместо 100.

In [35]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 500, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 34.2381694316864 seconds
relative error is:  0.0012929468270204054
np.allclose is:  False


In [36]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 29.061747074127197 seconds
relative error is:  0.0012929468269189366
np.allclose is:  False


In [ ]:
еще раз

In [37]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 2000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 49.91435885429382 seconds
relative error is:  0.0012929468268477534
np.allclose is:  False


дальше хуже

In [38]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1500, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 35.40580439567566 seconds
relative error is:  0.0012929468261462108
np.allclose is:  False


In [39]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 5000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 42.31066393852234 seconds
relative error is:  0.0012929468270844765
np.allclose is:  False


In [40]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 2500, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 170.01562643051147 seconds
relative error is:  0.0012929468269560196
np.allclose is:  False


что то очень долго

In [ ]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 10000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

#было 76 сек

In [42]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 68.9508113861084 seconds
relative error is:  0.0012929478419216546
np.allclose is:  False


In [43]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 2000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 51.05747628211975 seconds
relative error is:  0.0012929468268477534
np.allclose is:  False


теперь играемся с рангами 

In [44]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 32.79981875419617 seconds
relative error is:  0.0012929468269189366
np.allclose is:  False


In [45]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(25))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  24
execution time: 31.06197690963745 seconds
relative error is:  0.0017590538828481128
np.allclose is:  False


In [46]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(100))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  99
execution time: 35.308165311813354 seconds
relative error is:  0.0019052888115941241
np.allclose is:  False


In [50]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(200))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  196
execution time: 39.89589166641235 seconds
relative error is:  0.0016999733093508635
np.allclose is:  False


In [49]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(500))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  494
execution time: 59.254480838775635 seconds
relative error is:  0.0008295716541489007
np.allclose is:  False


In [48]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(1000))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  983
execution time: 145.97968673706055 seconds
relative error is:  0.002572079625545852
np.allclose is:  False


In [47]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(2000))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  1964
execution time: 263.4559862613678 seconds
relative error is:  0.0021647808668114592
np.allclose is:  False


теперь играемся с распределением рангов

In [51]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(5))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  5
execution time: 29.318974256515503 seconds
relative error is:  7.038144941697957e-16
np.allclose is:  True


In [58]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  50
execution time: 32.303749561309814 seconds
relative error is:  2.3824161481091742e-15
np.allclose is:  True


In [59]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.pareto(0.5,50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  7
execution time: 29.797606468200684 seconds
relative error is:  0.021481710765623344
np.allclose is:  False


In [52]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.pareto(1,50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  35
execution time: 31.170085668563843 seconds
relative error is:  0.01602111137613208
np.allclose is:  False


In [53]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.pareto(3,50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  47
execution time: 31.337493896484375 seconds
relative error is:  0.005916027471111141
np.allclose is:  False


In [55]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.pareto(10,50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  48
execution time: 32.6082022190094 seconds
relative error is:  0.0026045002055041853
np.allclose is:  False


In [56]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.pareto(20,50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  48
execution time: 32.04586386680603 seconds
relative error is:  0.0027646381804766577
np.allclose is:  False


теперь играемся с формой матрицы

In [71]:
A = construct_matrix(m=100000, n=1000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  50
execution time: 26.657194137573242 seconds
relative error is:  3.2659186822890186e-15
np.allclose is:  True


In [72]:
A = construct_matrix(m=1000000, n=100, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 100, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  50
execution time: 16.83628225326538 seconds
relative error is:  2.5399174067787194e-15
np.allclose is:  True


In [74]:
A = construct_matrix(m=10000000, n=10, singular_values=\
np.sort(np.random.rand(10))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 100000, 10, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  10
execution time: 7.501985788345337 seconds
relative error is:  6.506229550999398e-15
np.allclose is:  True


In [10]:
A = construct_matrix(m=10000000, n=10, singular_values=\
np.sort(np.random.rand(10))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 100000, 10, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  10
execution time: 6.114229917526245 seconds
relative error is:  4.6022376920220154e-15
np.allclose is:  True


In [76]:
A = construct_matrix(m=1000, n=100000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  10
execution time: 63.39677309989929 seconds
relative error is:  1.6893415847778152e-15
np.allclose is:  True


In [79]:
A = construct_matrix(m=1000, n=100000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 100, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 192.03041577339172 seconds
relative error is:  0.004013576216857179
np.allclose is:  False


In [83]:
A = construct_matrix(m=1000, n=100000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  50
execution time: 57.470436573028564 seconds
relative error is:  3.3644107176625417e-15
np.allclose is:  True


In [84]:
A = construct_matrix(m=1000, n=100000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 10000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  50
execution time: 63.68443441390991 seconds
relative error is:  2.761141014706199e-15
np.allclose is:  True


In [85]:
A = construct_matrix(m=1000, n=100000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 100, 10000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes


MemoryError: Unable to allocate 74.5 GiB for an array with shape (100000, 100000) and data type float64

In [ ]:
# ошибка, число столбцов не может быть слишком большой относительно числа строк. 100x1000 тоже не работает

In [96]:
A = construct_matrix(m=1000, n=100000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 100, 100, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes


MemoryError: Unable to allocate 74.5 GiB for an array with shape (100000, 100000) and data type float64

In [8]:
A = construct_matrix(m=1000, n=100000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 100, 100, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes


MemoryError: Unable to allocate 74.5 GiB for an array with shape (100000, 100000) and data type float64

In [13]:
A = construct_matrix(m=10000, n=100000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  7629.39453125 megabytes
rank of matrix approximation is:  50
execution time: 400.6256878376007 seconds
relative error is:  2.6698375614245413e-15


MemoryError: Unable to allocate 7.45 GiB for an array with shape (10000, 100000) and data type float64

In [ ]:
A = construct_matrix(m=10000, n=100000, singular_values=\
np.sort(np.random.rand(50))[::-1])
timeit(np.linalg.svd)(A, full_matrices = False) #считался 40 минут, так и не досчитался

matrix has memory of  7629.39453125 megabytes


In [7]:
A = construct_matrix(m=10000000, n=10, singular_values=\
np.sort(np.random.rand(10))[::-1])
timeit(np.linalg.svd)(A, full_matrices = False)

matrix has memory of  762.939453125 megabytes
execution time: 2.3006808757781982 seconds


(array([[-2.05093529e-04,  5.54990937e-04,  1.50421395e-04, ...,
          1.55865532e-02,  1.39510158e-01,  7.44419103e-02],
        [-8.54206670e-05, -4.87824287e-05,  7.09777168e-04, ...,
          3.98941940e-02,  5.80642156e-02,  4.64002135e-02],
        [-1.12718141e-05,  7.90771990e-04,  3.73970337e-04, ...,
          7.71514666e-01, -4.37330890e-01,  3.26050908e-01],
        ...,
        [-3.47000586e-04,  3.89795268e-04, -2.91691025e-04, ...,
         -4.76764233e-05,  1.86408576e-04,  4.07070543e-05],
        [-1.14325668e-04,  2.75739153e-04,  5.57624088e-04, ...,
         -1.47530186e-05, -5.30555837e-05, -2.33793446e-06],
        [-3.63089808e-05,  3.12180858e-04,  2.02645786e-04, ...,
         -1.62460627e-05, -3.02950400e-05, -8.24181238e-05]]),
 array([9.62748423e-01, 3.28161439e-01, 2.23365007e-01, 1.53910495e-01,
        8.70453252e-02, 7.85542229e-16, 2.52170720e-16, 2.32431308e-16,
        1.09931645e-16, 8.13748806e-17]),
 array([[-0.42892598, -0.44603139, -0.42975

In [4]:
A = construct_matrix(m=1000, n=100000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 100, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  50
execution time: 98.38085436820984 seconds
relative error is:  2.6883061734873016e-15
np.allclose is:  True


In [5]:
A = construct_matrix(m=1000, n=100000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  50
execution time: 47.382139444351196 seconds
relative error is:  3.3644107176625417e-15
np.allclose is:  True


In [7]:
A = construct_matrix(m=1000, n=100000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 500, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  50
execution time: 131.5382969379425 seconds
relative error is:  2.7811998009537213e-15
np.allclose is:  True


In [8]:
A = construct_matrix(m=1000, n=100000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 5000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  50
execution time: 64.61932921409607 seconds
relative error is:  2.9544097676172203e-15
np.allclose is:  True


In [10]:
A = construct_matrix(m=100, n=1000000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 100, 5000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 32.1997344493866 seconds
relative error is:  0.0023415085166258527
np.allclose is:  False


In [11]:
A = construct_matrix(m=100, n=1000000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 100, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 52.73057317733765 seconds
relative error is:  0.002311029090222684
np.allclose is:  False


In [12]:
A = construct_matrix(m=100, n=1000000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 100, 10000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 41.325549364089966 seconds
relative error is:  0.0023110290898854906
np.allclose is:  False


In [13]:
A = construct_matrix(m=100, n=1000000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 100, 7500, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 38.70057535171509 seconds
relative error is:  0.0023110290935960034
np.allclose is:  False


In [14]:
A = construct_matrix(m=100, n=1000000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 100, 2500, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 71.43722009658813 seconds
relative error is:  0.0023110290899499954
np.allclose is:  False


In [17]:
timeit(np.linalg.svd)(A, full_matrices = False) 

execution time: 14.164824962615967 seconds


(array([[ 0.06815859, -0.16024581,  0.01614457, ...,  0.0025521 ,
         -0.1072634 ,  0.00103778],
        [ 0.17644443, -0.0129171 ,  0.04948115, ..., -0.03746337,
         -0.00191714,  0.03202555],
        [ 0.00571946, -0.14613841, -0.01972624, ...,  0.04144061,
         -0.06091884,  0.02471881],
        ...,
        [ 0.17856867,  0.08295949,  0.06755205, ...,  0.05134356,
         -0.08770188, -0.17359836],
        [ 0.00110044, -0.11427211, -0.04758337, ...,  0.150144  ,
         -0.1740547 ,  0.11077851],
        [ 0.07189157,  0.05780384,  0.07150595, ...,  0.16697934,
         -0.04966171, -0.01805851]]),
 array([9.97602087e-01, 9.96781695e-01, 9.94104852e-01, 9.60988009e-01,
        9.31625374e-01, 8.70659508e-01, 8.43657829e-01, 8.19933659e-01,
        8.18766866e-01, 8.09810844e-01, 7.98670168e-01, 7.96021699e-01,
        7.72163876e-01, 7.37804365e-01, 7.31397833e-01, 6.75843948e-01,
        6.67920218e-01, 6.50305937e-01, 6.43980994e-01, 6.10654930e-01,
        6.073

In [2]:
A = construct_matrix(m=100, n=10000000, singular_values=\
np.sort(np.random.rand(50))[::-1])

matrix has memory of  7629.39453125 megabytes


In [20]:
timeit(np.linalg.svd)(A, full_matrices = False) 

execution time: 0.01882195472717285 seconds


(array([[ 9.68607557e-312,  9.68476457e-312, -7.52899700e-002, ...,
         -4.23952752e-015,  6.49480469e-015,  3.54685899e-015],
        [-1.34457843e-001, -4.16390280e-002, -8.67106411e-002, ...,
         -9.71521418e-002, -1.53018797e-002,  1.16190860e-001],
        [-4.21656883e-002,  7.62893864e-002, -2.67522459e-002, ...,
          2.47656893e-002, -9.22745815e-002,  1.82879026e-002],
        ...,
        [-4.34400898e-002, -1.38856275e-001, -1.54118461e-001, ...,
          4.85503419e-002,  3.80176274e-002,  1.20824249e-002],
        [-2.50251550e-002,  4.02812255e-002, -3.95650566e-002, ...,
         -4.45347146e-002, -6.58384603e-002,  1.25764088e-001],
        [ 8.53581362e-003, -7.11783249e-002, -3.68274537e-002, ...,
         -1.62252248e-002,  7.35761910e-002,  5.52162461e-002]]),
 array([9.97602087e-01, 9.96781695e-01, 9.94104852e-01, 9.60988009e-01,
        9.31625374e-01, 8.70659508e-01, 8.43657829e-01, 8.19933659e-01,
        8.18766866e-01, 8.09810844e-01, 7.9867016

In [ ]:
U_aprx, S_aprx, V_aprx = blockSVD(A, 100, 5000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

rank of matrix approximation is:  50
execution time: 405.8230426311493 seconds
relative error is:  2.7948321552104536e-15


In [5]:
A = construct_matrix(m=10, n=10000000, singular_values=\
np.sort(np.random.rand(10))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  10
execution time: 44.49514293670654 seconds
relative error is:  1.6598916134332804e-15
np.allclose is:  True


In [8]:
A = construct_matrix(m=10, n=10000000, singular_values=\
np.sort(np.random.rand(10))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10, 100000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  10
execution time: 15.208763360977173 seconds
relative error is:  1.325365791678646e-15
np.allclose is:  True


In [9]:
A = construct_matrix(m=10, n=10000000, singular_values=\
np.sort(np.random.rand(10))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10, 1000000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  10
execution time: 14.34555435180664 seconds
relative error is:  1.1081298943366356e-15
np.allclose is:  True
