In [1]:
import numpy as np
import time
from BlockSVD import *

In [32]:
A = construct_matrix(m=50000, n=5000, singular_values=\
[1, 0.8, 0.7, 0.5, 0.1, 0.05, 0.01, 0.001, 0.0000001, 0.0000000001])
U_aprx, S_aprx, V_aprx = blockSVD(A, 200, 200, gamma=0.0001)
quality(A, U_aprx, S_aprx, V_aprx)
timeit(np.linalg.svd)(A)

matrix has memory of  1907.3486328125 megabytes
rank of matrix approximation is:  8
execution time: 130.198477268219 seconds
relative error is:  6.464948612601192e-08
np.allclose is:  True
execution time: 0.06563591957092285 seconds


(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([1.05750034e-311, 1.05703884e-311, 0.00000000e+000, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]))

In [48]:
A = construct_matrix(m=5000, n=5000, singular_values=\
[1, 0.8, 0.7, 0.5, 0.1, 0.05, 0.01, 0.001, 0.0000001, 0.0000000001])
timeit(np.linalg.svd)(A)

matrix has memory of  190.73486328125 megabytes
execution time: 33.962015867233276 seconds


(array([[-9.24090431e-03, -2.50988986e-02, -6.43965563e-03, ...,
          1.36885816e-02,  3.23927058e-01,  3.93236063e-01],
        [-5.07874411e-04, -3.55151063e-02, -1.66312645e-02, ...,
          5.05546483e-02, -1.38431660e-01, -1.68188031e-01],
        [-1.50960438e-02,  1.15823112e-02,  1.57942524e-03, ...,
         -5.52658393e-01, -3.06027596e-01,  1.34584733e-02],
        ...,
        [-7.19626422e-03, -2.91187072e-02,  4.34466894e-03, ...,
          6.02471640e-03,  8.65784741e-03, -2.27941668e-03],
        [-5.27311112e-03,  1.88305360e-03, -1.89058058e-02, ...,
         -3.45634983e-03, -7.01261022e-04,  5.42884622e-03],
        [-1.31514741e-02, -2.43342704e-04, -6.22694619e-03, ...,
         -4.98852703e-03,  4.12666065e-03, -6.40577404e-03]]),
 array([1.00000000e+00, 8.00000000e-01, 7.00000000e-01, ...,
        5.25030347e-17, 5.14993022e-17, 1.41370598e-17]),
 array([[-2.07234945e-02, -2.39688366e-02, -8.71496272e-03, ...,
         -2.20021443e-03, -2.22715356e-02, -1

In [49]:
A = construct_matrix(m=10000, n=5000, singular_values=\
[1, 0.8, 0.7, 0.5, 0.1, 0.05, 0.01, 0.001, 0.0000001, 0.0000000001])
timeit(np.linalg.svd)(A)

matrix has memory of  381.4697265625 megabytes
execution time: 66.22969841957092 seconds


(array([[-6.50597557e-03,  1.75499880e-02,  4.60454356e-03, ...,
          8.11940289e-04,  1.50213986e-03,  4.59910655e-05],
        [-3.57564411e-04,  2.48774290e-02,  1.17859844e-02, ...,
          1.26517849e-03, -1.69102776e-04, -1.77010442e-03],
        [-1.06282339e-02, -8.16664270e-03, -1.05266805e-03, ...,
          7.64423467e-04,  1.77741461e-03,  2.34194216e-03],
        ...,
        [-1.56250279e-03,  6.76217251e-04,  2.00169485e-02, ...,
          4.95281576e-01,  4.47028548e-03, -3.77965392e-03],
        [-1.58163386e-02,  4.68113296e-03, -1.29832045e-02, ...,
          2.91871843e-03,  3.94723760e-01,  7.39252807e-03],
        [-1.36173275e-02, -1.18722057e-02,  1.55086879e-02, ...,
         -7.95798023e-04,  2.90996579e-03,  3.85949888e-01]]),
 array([1.00000000e+00, 8.00000000e-01, 7.00000000e-01, ...,
        9.74685144e-17, 7.07838539e-17, 3.52096463e-18]),
 array([[-1.40819131e-02, -2.58378953e-04, -1.88065894e-02, ...,
         -6.58229733e-03, -2.91633142e-03, -1

Experiment start

In [53]:
A = construct_matrix(m=20000, n=5000, singular_values=\
[1, 0.8, 0.7, 0.5, 0.1, 0.05, 0.01, 0.001, 0.0000001, 0.0000000001])
timeit(np.linalg.svd)(A)

matrix has memory of  762.939453125 megabytes
execution time: 137.2986855506897 seconds


(array([[ 4.57287587e-03, -1.24340190e-02, -3.32253237e-03, ...,
          1.12906075e-03,  2.59525508e-04, -2.55907254e-04],
        [ 2.51322442e-04, -1.76624895e-02, -8.37667098e-03, ...,
         -1.80442246e-03,  9.41883414e-04, -1.13950901e-03],
        [ 7.47030077e-03,  5.84305606e-03,  6.87277486e-04, ...,
         -1.09454715e-04,  2.84228510e-04, -3.84961402e-04],
        ...,
        [ 9.91434815e-04, -8.62170340e-03, -1.32464664e-02, ...,
          7.06233610e-01, -3.71717051e-03, -2.00543674e-03],
        [ 7.63907598e-03, -9.88608109e-03, -3.54413868e-03, ...,
         -4.86857665e-03,  7.34837373e-01, -1.28762751e-05],
        [ 1.09926995e-02, -3.13910124e-03,  1.02217770e-02, ...,
         -3.44055582e-03,  3.10274598e-03,  6.41372047e-01]]),
 array([1.00000000e+00, 8.00000000e-01, 7.00000000e-01, ...,
        4.94825388e-17, 4.81965305e-17, 3.54916128e-18]),
 array([[ 6.91378704e-03,  3.51115028e-03,  1.82455811e-02, ...,
          1.44202919e-02,  1.48766215e-02,  1

In [54]:
A = construct_matrix(m=20000, n=5000, singular_values=\
[1, 0.8, 0.7, 0.5, 0.1, 0.05, 0.01, 0.001, 0.0000001, 0.0000000001])
U_aprx, S_aprx, V_aprx = blockSVD(A, 200, 200, gamma=0.0001)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  8
execution time: 49.631569385528564 seconds
relative error is:  6.464948612601911e-08
np.allclose is:  True


Experiment end

In [4]:
A = construct_matrix(m=10000, n=10000, singular_values=\
[1, 0.8, 0.7, 0.5, 0.1, 0.05, 0.01, 0.001, 0.0000001, 0.0000000001])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 1000, gamma=0.0001)
quality(A, U_aprx, S_aprx, V_aprx) 


matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  8
execution time: 49.82099914550781 seconds
relative error is:  6.464948612604958e-08
np.allclose is:  True


In [12]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 1000, gamma=0.0001)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  50
execution time: 75.3153235912323 seconds
relative error is:  2.70859472652553e-15
np.allclose is:  True


In [13]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 1000, gamma=0.1)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  46
execution time: 71.00275611877441 seconds
relative error is:  0.029184005594171746
np.allclose is:  False


In [15]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 1000, gamma=0.5)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  21
execution time: 65.29420185089111 seconds
relative error is:  0.46530928759673046
np.allclose is:  False


In [14]:
timeit(np.linalg.svd)(A)

execution time: 231.5099368095398 seconds


(array([[-0.00645551, -0.01752166,  0.00444191, ...,  0.04414777,
         -0.03483861,  0.01572275],
        [-0.0167116 , -0.00124084,  0.00545271, ..., -0.00140898,
          0.02765656,  0.0063791 ],
        [-0.00054171, -0.01603576,  0.00054633, ..., -0.03157257,
         -0.00855204,  0.01565269],
        ...,
        [-0.00562592, -0.0007968 ,  0.01764564, ..., -0.00398922,
         -0.00319246,  0.00707451],
        [-0.00816887, -0.01350602, -0.01610023, ...,  0.00484463,
         -0.00072118, -0.01800656],
        [-0.01563713,  0.00758123,  0.01065396, ..., -0.00256852,
          0.00769256, -0.00239902]]),
 array([9.84533274e-01, 8.96570411e-01, 8.93943542e-01, ...,
        1.69151984e-17, 1.49698212e-17, 5.79307360e-18]),
 array([[-5.19052662e-03, -1.60355643e-02, -1.02935599e-02, ...,
         -1.34664824e-02, -5.03943241e-03, -1.55933196e-02],
        [ 7.51084571e-03, -8.28092562e-03,  6.34353432e-03, ...,
         -1.26847763e-02,  1.31221422e-02,  1.50143180e-03],
  

In [25]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.pareto(5, 50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 1000, gamma=0.0001)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  50
execution time: 69.13762140274048 seconds
relative error is:  2.80186809997225e-15
np.allclose is:  True


In [26]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.pareto(5, 50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 1000, gamma=0.1)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  28
execution time: 63.27093744277954 seconds
relative error is:  0.13678694039493008
np.allclose is:  False


In [27]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.pareto(5, 50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 1000, gamma=0.05)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  36
execution time: 65.5826427936554 seconds
relative error is:  0.0760187324143413
np.allclose is:  False


внизу считалось ужасно долго (~20 мин)

In [28]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10, 10, gamma=0.5)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes


KeyboardInterrupt: 

Do column-wise and row-wise partitions and see column-wise partitions are better

In [29]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 100, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 118.20474767684937 seconds
relative error is:  0.001292946826372431
np.allclose is:  False


In [30]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 100, 10000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 162.28913593292236 seconds
relative error is:  0.0012929468264108344
np.allclose is:  False


proceed with column-wise partition + row-wise partition of size 2

In [32]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 5000, 100, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 88.3730628490448 seconds
relative error is:  0.0012929468266200976
np.allclose is:  False


делим строку еще по 2.

In [33]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 2500, 100, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 93.86327385902405 seconds
relative error is:  0.001292946826450673
np.allclose is:  False


 делим строку еще по 2.

In [34]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1250, 100, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 133.7633466720581 seconds
relative error is:  0.0012929468261506213
np.allclose is:  False


дальше хуже

попробуем по колонкам только поделить, но сделать 500 вместо 100.

In [35]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 500, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 34.2381694316864 seconds
relative error is:  0.0012929468270204054
np.allclose is:  False


In [36]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 29.061747074127197 seconds
relative error is:  0.0012929468269189366
np.allclose is:  False


In [ ]:
еще раз

In [37]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 2000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 49.91435885429382 seconds
relative error is:  0.0012929468268477534
np.allclose is:  False


дальше хуже

In [38]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1500, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 35.40580439567566 seconds
relative error is:  0.0012929468261462108
np.allclose is:  False


In [39]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 5000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 42.31066393852234 seconds
relative error is:  0.0012929468270844765
np.allclose is:  False


In [40]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 2500, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 170.01562643051147 seconds
relative error is:  0.0012929468269560196
np.allclose is:  False


что то очень долго

In [ ]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 10000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

#было 76 сек

In [42]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 68.9508113861084 seconds
relative error is:  0.0012929478419216546
np.allclose is:  False


In [43]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 2000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 51.05747628211975 seconds
relative error is:  0.0012929468268477534
np.allclose is:  False


теперь играемся с рангами 

In [44]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 32.79981875419617 seconds
relative error is:  0.0012929468269189366
np.allclose is:  False


In [45]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(25))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  24
execution time: 31.06197690963745 seconds
relative error is:  0.0017590538828481128
np.allclose is:  False


In [46]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(100))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  99
execution time: 35.308165311813354 seconds
relative error is:  0.0019052888115941241
np.allclose is:  False


In [50]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(200))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  196
execution time: 39.89589166641235 seconds
relative error is:  0.0016999733093508635
np.allclose is:  False


In [49]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(500))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  494
execution time: 59.254480838775635 seconds
relative error is:  0.0008295716541489007
np.allclose is:  False


In [48]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(1000))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  983
execution time: 145.97968673706055 seconds
relative error is:  0.002572079625545852
np.allclose is:  False


In [47]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(2000))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  1964
execution time: 263.4559862613678 seconds
relative error is:  0.0021647808668114592
np.allclose is:  False


теперь играемся с распределением рангов

In [51]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(5))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  5
execution time: 29.318974256515503 seconds
relative error is:  7.038144941697957e-16
np.allclose is:  True


In [58]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  50
execution time: 32.303749561309814 seconds
relative error is:  2.3824161481091742e-15
np.allclose is:  True


In [59]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.pareto(0.5,50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  7
execution time: 29.797606468200684 seconds
relative error is:  0.021481710765623344
np.allclose is:  False


In [52]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.pareto(1,50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  35
execution time: 31.170085668563843 seconds
relative error is:  0.01602111137613208
np.allclose is:  False


In [53]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.pareto(3,50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  47
execution time: 31.337493896484375 seconds
relative error is:  0.005916027471111141
np.allclose is:  False


In [55]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.pareto(10,50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  48
execution time: 32.6082022190094 seconds
relative error is:  0.0026045002055041853
np.allclose is:  False


In [56]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.pareto(20,50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  48
execution time: 32.04586386680603 seconds
relative error is:  0.0027646381804766577
np.allclose is:  False


теперь играемся с формой матрицы

In [71]:
A = construct_matrix(m=100000, n=1000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  50
execution time: 26.657194137573242 seconds
relative error is:  3.2659186822890186e-15
np.allclose is:  True


In [72]:
A = construct_matrix(m=1000000, n=100, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 100, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  50
execution time: 16.83628225326538 seconds
relative error is:  2.5399174067787194e-15
np.allclose is:  True


In [74]:
A = construct_matrix(m=10000000, n=10, singular_values=\
np.sort(np.random.rand(10))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 100000, 10, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  10
execution time: 7.501985788345337 seconds
relative error is:  6.506229550999398e-15
np.allclose is:  True


In [10]:
A = construct_matrix(m=10000000, n=10, singular_values=\
np.sort(np.random.rand(10))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 100000, 10, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  10
execution time: 6.114229917526245 seconds
relative error is:  4.6022376920220154e-15
np.allclose is:  True


In [76]:
A = construct_matrix(m=1000, n=100000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  10
execution time: 63.39677309989929 seconds
relative error is:  1.6893415847778152e-15
np.allclose is:  True


In [79]:
A = construct_matrix(m=1000, n=100000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 100, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 192.03041577339172 seconds
relative error is:  0.004013576216857179
np.allclose is:  False


In [83]:
A = construct_matrix(m=1000, n=100000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  50
execution time: 57.470436573028564 seconds
relative error is:  3.3644107176625417e-15
np.allclose is:  True


In [84]:
A = construct_matrix(m=1000, n=100000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 10000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  50
execution time: 63.68443441390991 seconds
relative error is:  2.761141014706199e-15
np.allclose is:  True


In [85]:
A = construct_matrix(m=1000, n=100000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 100, 10000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes


MemoryError: Unable to allocate 74.5 GiB for an array with shape (100000, 100000) and data type float64

In [ ]:
# ошибка, число столбцов не может быть слишком большой относительно числа строк. 100x1000 тоже не работает

In [96]:
A = construct_matrix(m=1000, n=100000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 100, 100, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes


MemoryError: Unable to allocate 74.5 GiB for an array with shape (100000, 100000) and data type float64

In [8]:
A = construct_matrix(m=1000, n=100000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 100, 100, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes


MemoryError: Unable to allocate 74.5 GiB for an array with shape (100000, 100000) and data type float64

In [13]:
A = construct_matrix(m=10000, n=100000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  7629.39453125 megabytes
rank of matrix approximation is:  50
execution time: 400.6256878376007 seconds
relative error is:  2.6698375614245413e-15


MemoryError: Unable to allocate 7.45 GiB for an array with shape (10000, 100000) and data type float64

In [ ]:
A = construct_matrix(m=10000, n=100000, singular_values=\
np.sort(np.random.rand(50))[::-1])
timeit(np.linalg.svd)(A, full_matrices = False) #считался 40 минут, так и не досчитался

matrix has memory of  7629.39453125 megabytes


In [7]:
A = construct_matrix(m=10000000, n=10, singular_values=\
np.sort(np.random.rand(10))[::-1])
timeit(np.linalg.svd)(A, full_matrices = False)

matrix has memory of  762.939453125 megabytes
execution time: 2.3006808757781982 seconds


(array([[-2.05093529e-04,  5.54990937e-04,  1.50421395e-04, ...,
          1.55865532e-02,  1.39510158e-01,  7.44419103e-02],
        [-8.54206670e-05, -4.87824287e-05,  7.09777168e-04, ...,
          3.98941940e-02,  5.80642156e-02,  4.64002135e-02],
        [-1.12718141e-05,  7.90771990e-04,  3.73970337e-04, ...,
          7.71514666e-01, -4.37330890e-01,  3.26050908e-01],
        ...,
        [-3.47000586e-04,  3.89795268e-04, -2.91691025e-04, ...,
         -4.76764233e-05,  1.86408576e-04,  4.07070543e-05],
        [-1.14325668e-04,  2.75739153e-04,  5.57624088e-04, ...,
         -1.47530186e-05, -5.30555837e-05, -2.33793446e-06],
        [-3.63089808e-05,  3.12180858e-04,  2.02645786e-04, ...,
         -1.62460627e-05, -3.02950400e-05, -8.24181238e-05]]),
 array([9.62748423e-01, 3.28161439e-01, 2.23365007e-01, 1.53910495e-01,
        8.70453252e-02, 7.85542229e-16, 2.52170720e-16, 2.32431308e-16,
        1.09931645e-16, 8.13748806e-17]),
 array([[-0.42892598, -0.44603139, -0.42975

In [4]:
A = construct_matrix(m=1000, n=100000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 100, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  50
execution time: 98.38085436820984 seconds
relative error is:  2.6883061734873016e-15
np.allclose is:  True


In [5]:
A = construct_matrix(m=1000, n=100000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  50
execution time: 47.382139444351196 seconds
relative error is:  3.3644107176625417e-15
np.allclose is:  True


In [7]:
A = construct_matrix(m=1000, n=100000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 500, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  50
execution time: 131.5382969379425 seconds
relative error is:  2.7811998009537213e-15
np.allclose is:  True


In [8]:
A = construct_matrix(m=1000, n=100000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 5000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  50
execution time: 64.61932921409607 seconds
relative error is:  2.9544097676172203e-15
np.allclose is:  True


In [10]:
A = construct_matrix(m=100, n=1000000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 100, 5000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 32.1997344493866 seconds
relative error is:  0.0023415085166258527
np.allclose is:  False


In [11]:
A = construct_matrix(m=100, n=1000000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 100, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 52.73057317733765 seconds
relative error is:  0.002311029090222684
np.allclose is:  False


In [12]:
A = construct_matrix(m=100, n=1000000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 100, 10000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 41.325549364089966 seconds
relative error is:  0.0023110290898854906
np.allclose is:  False


In [13]:
A = construct_matrix(m=100, n=1000000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 100, 7500, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 38.70057535171509 seconds
relative error is:  0.0023110290935960034
np.allclose is:  False


In [14]:
A = construct_matrix(m=100, n=1000000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 100, 2500, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 71.43722009658813 seconds
relative error is:  0.0023110290899499954
np.allclose is:  False


In [17]:
timeit(np.linalg.svd)(A, full_matrices = False) 

execution time: 14.164824962615967 seconds


(array([[ 0.06815859, -0.16024581,  0.01614457, ...,  0.0025521 ,
         -0.1072634 ,  0.00103778],
        [ 0.17644443, -0.0129171 ,  0.04948115, ..., -0.03746337,
         -0.00191714,  0.03202555],
        [ 0.00571946, -0.14613841, -0.01972624, ...,  0.04144061,
         -0.06091884,  0.02471881],
        ...,
        [ 0.17856867,  0.08295949,  0.06755205, ...,  0.05134356,
         -0.08770188, -0.17359836],
        [ 0.00110044, -0.11427211, -0.04758337, ...,  0.150144  ,
         -0.1740547 ,  0.11077851],
        [ 0.07189157,  0.05780384,  0.07150595, ...,  0.16697934,
         -0.04966171, -0.01805851]]),
 array([9.97602087e-01, 9.96781695e-01, 9.94104852e-01, 9.60988009e-01,
        9.31625374e-01, 8.70659508e-01, 8.43657829e-01, 8.19933659e-01,
        8.18766866e-01, 8.09810844e-01, 7.98670168e-01, 7.96021699e-01,
        7.72163876e-01, 7.37804365e-01, 7.31397833e-01, 6.75843948e-01,
        6.67920218e-01, 6.50305937e-01, 6.43980994e-01, 6.10654930e-01,
        6.073

In [2]:
A = construct_matrix(m=100, n=10000000, singular_values=\
np.sort(np.random.rand(50))[::-1])

matrix has memory of  7629.39453125 megabytes


In [20]:
timeit(np.linalg.svd)(A, full_matrices = False) 

execution time: 0.01882195472717285 seconds


(array([[ 9.68607557e-312,  9.68476457e-312, -7.52899700e-002, ...,
         -4.23952752e-015,  6.49480469e-015,  3.54685899e-015],
        [-1.34457843e-001, -4.16390280e-002, -8.67106411e-002, ...,
         -9.71521418e-002, -1.53018797e-002,  1.16190860e-001],
        [-4.21656883e-002,  7.62893864e-002, -2.67522459e-002, ...,
          2.47656893e-002, -9.22745815e-002,  1.82879026e-002],
        ...,
        [-4.34400898e-002, -1.38856275e-001, -1.54118461e-001, ...,
          4.85503419e-002,  3.80176274e-002,  1.20824249e-002],
        [-2.50251550e-002,  4.02812255e-002, -3.95650566e-002, ...,
         -4.45347146e-002, -6.58384603e-002,  1.25764088e-001],
        [ 8.53581362e-003, -7.11783249e-002, -3.68274537e-002, ...,
         -1.62252248e-002,  7.35761910e-002,  5.52162461e-002]]),
 array([9.97602087e-01, 9.96781695e-01, 9.94104852e-01, 9.60988009e-01,
        9.31625374e-01, 8.70659508e-01, 8.43657829e-01, 8.19933659e-01,
        8.18766866e-01, 8.09810844e-01, 7.9867016

In [ ]:
U_aprx, S_aprx, V_aprx = blockSVD(A, 100, 5000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

rank of matrix approximation is:  50
execution time: 405.8230426311493 seconds
relative error is:  2.7948321552104536e-15


In [5]:
A = construct_matrix(m=10, n=10000000, singular_values=\
np.sort(np.random.rand(10))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  10
execution time: 44.49514293670654 seconds
relative error is:  1.6598916134332804e-15
np.allclose is:  True


In [8]:
A = construct_matrix(m=10, n=10000000, singular_values=\
np.sort(np.random.rand(10))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10, 100000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  10
execution time: 15.208763360977173 seconds
relative error is:  1.325365791678646e-15
np.allclose is:  True


In [9]:
A = construct_matrix(m=10, n=10000000, singular_values=\
np.sort(np.random.rand(10))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10, 1000000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  10
execution time: 14.34555435180664 seconds
relative error is:  1.1081298943366356e-15
np.allclose is:  True


In [10]:
A = construct_matrix(m=10, n=10000000, singular_values=\
np.sort(np.random.rand(10))[::-1])
timeit(np.linalg.svd)(A, full_matrices = False) 

matrix has memory of  762.939453125 megabytes
execution time: 4.043733358383179 seconds


(array([[-0.20476003,  0.46791825, -0.09898519,  0.01672616, -0.35938116,
          0.52090212, -0.09898764,  0.45810392,  0.08449834,  0.31899286],
        [-0.01125349,  0.64104822,  0.03456666,  0.15380457,  0.1596036 ,
         -0.2361641 , -0.01034554, -0.22421966, -0.64816616,  0.11105043],
        [-0.33449826, -0.18348828,  0.15405076,  0.02335539,  0.07255162,
         -0.57539519, -0.283905  ,  0.32697969,  0.0514379 ,  0.55105251],
        [-0.33214307, -0.16073056, -0.1467139 , -0.43079191,  0.39423473,
          0.23265843, -0.37393719,  0.25077655, -0.38489824, -0.3103619 ],
        [-0.06671796,  0.27678381, -0.45811054, -0.48787294, -0.33520468,
         -0.49048604,  0.13726202,  0.08403261,  0.15486168, -0.26121054],
        [-0.5300692 ,  0.08076804,  0.26614204, -0.0518838 , -0.31095076,
          0.05412372, -0.37658907, -0.5892603 ,  0.18208943, -0.13098211],
        [-0.21248879,  0.0059725 ,  0.68421054, -0.13068058, -0.18400638,
         -0.06644272,  0.4650144

In [11]:
A = construct_matrix(m=100, n=1000000, singular_values=\
np.sort(np.random.rand(10))[::-1])
timeit(np.linalg.svd)(A, full_matrices = False) 

matrix has memory of  762.939453125 megabytes
execution time: 14.161437749862671 seconds


(array([[-6.84430094e-02, -1.45136176e-01,  4.54981454e-02, ...,
         -4.99476349e-15, -1.95814338e-01,  7.03980263e-01],
        [-3.76158565e-03, -2.14657559e-01,  1.05331126e-01, ...,
          3.92721406e-02,  2.62263363e-02, -8.98464837e-02],
        [-1.11809260e-01,  8.12846090e-02,  1.95019098e-02, ...,
         -2.80515878e-02, -1.86769277e-03, -3.64357521e-02],
        ...,
        [-1.21278468e-01, -8.87515456e-02,  2.33417001e-02, ...,
          4.01451615e-03,  1.75443470e-01,  2.99435803e-02],
        [-6.10793253e-02, -1.12062516e-01, -1.24976337e-01, ...,
         -4.96829623e-02,  3.92333344e-02, -2.05498516e-02],
        [-1.46084293e-01, -9.21281815e-03, -9.76106379e-02, ...,
         -2.46829278e-02,  1.08945102e-01,  2.26027438e-02]]),
 array([9.62748423e-01, 7.44628331e-01, 5.94720116e-01, 4.31099789e-01,
        3.28161439e-01, 2.88582912e-01, 2.23365007e-01, 1.53910495e-01,
        1.47087257e-01, 8.70453252e-02, 1.88651102e-15, 1.27162099e-15,
        9.793

In [12]:
A = construct_matrix(m=1000, n=100000, singular_values=\
np.sort(np.random.rand(10))[::-1])
timeit(np.linalg.svd)(A, full_matrices = False) 

matrix has memory of  762.939453125 megabytes
execution time: 12.946063756942749 seconds


(array([[-0.02127115,  0.05312401, -0.01392251, ...,  0.245398  ,
         -0.22218997,  0.57281019],
        [-0.00116905,  0.07565365, -0.03600481, ...,  0.10647135,
          0.19321381, -0.08114277],
        [-0.03474879, -0.02525874,  0.00262722, ..., -0.01729941,
         -0.02051416,  0.01802453],
        ...,
        [-0.00378399,  0.07340987, -0.04534541, ...,  0.08394108,
          0.06152268,  0.03011158],
        [-0.02009926,  0.02681456,  0.00958349, ..., -0.0095507 ,
         -0.00688142,  0.00805101],
        [-0.02557849, -0.00096127, -0.01245334, ..., -0.00419769,
         -0.01838164, -0.01531923]]),
 array([8.44012092e-01, 8.13468028e-01, 7.98633822e-01, 6.70935677e-01,
        5.89098352e-01, 5.07252861e-01, 4.89370411e-01, 4.85438537e-01,
        3.36365184e-01, 2.02824084e-01, 7.49633326e-16, 3.09360194e-16,
        2.92114848e-16, 2.72952296e-16, 2.56978463e-16, 2.43946513e-16,
        2.42429900e-16, 2.37278263e-16, 2.24742070e-16, 2.12051123e-16,
        2.115

In [13]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(10))[::-1])
timeit(np.linalg.svd)(A, full_matrices = False) 

matrix has memory of  762.939453125 megabytes
execution time: 248.0271987915039 seconds


(array([[-0.00650598,  0.01754999,  0.00460454, ..., -0.06142705,
          0.00883209,  0.00779284],
        [-0.00035756,  0.02487743,  0.01178598, ...,  0.03428767,
          0.06081512,  0.0045491 ],
        [-0.01062823, -0.00816664, -0.00105267, ...,  0.05556431,
          0.01926617,  0.00958843],
        ...,
        [-0.0015625 ,  0.00067622,  0.02001695, ...,  0.00069095,
          0.00975289, -0.00033107],
        [-0.01581634,  0.00468113, -0.0129832 , ..., -0.00902599,
         -0.013501  ,  0.00746056],
        [-0.01361733, -0.01187221,  0.01550869, ..., -0.00563358,
          0.00983175, -0.00187349]]),
 array([6.22146144e-01, 6.12202996e-01, 5.69124307e-01, ...,
        4.27240756e-17, 3.25735333e-17, 7.21952455e-18]),
 array([[-0.00996873, -0.00018291, -0.01331338, ..., -0.00139381,
         -0.01073937, -0.01545405],
        [ 0.00243274,  0.02265893, -0.00825565, ...,  0.01223619,
          0.01397704,  0.00436747],
        [ 0.00360778,  0.00381297, -0.00487957, ..

In [14]:
A = construct_matrix(m=100000, n=1000, singular_values=\
np.sort(np.random.rand(10))[::-1])
timeit(np.linalg.svd)(A, full_matrices = False) 

matrix has memory of  762.939453125 megabytes
execution time: 10.113072633743286 seconds


(array([[ 0.00205211, -0.00554365, -0.00149952, ...,  0.02689217,
         -0.00946165,  0.03803366],
        [ 0.00011278, -0.00789943, -0.00374799, ..., -0.00257747,
         -0.00873037, -0.00353969],
        [ 0.00335235,  0.00264313,  0.00029217, ..., -0.01857207,
         -0.00802959, -0.00941449],
        ...,
        [ 0.00327937, -0.00083651,  0.0009791 , ...,  0.00152193,
          0.00094597,  0.00041375],
        [ 0.00214198,  0.00132039, -0.00633604, ...,  0.00385857,
          0.00023983,  0.00384246],
        [ 0.00270509, -0.00464661,  0.00545616, ..., -0.00112554,
          0.00537015, -0.0054242 ]]),
 array([8.86300678e-01, 5.78407302e-01, 4.78112565e-01, 4.58676591e-01,
        4.46837025e-01, 2.82587967e-01, 2.77595304e-01, 2.03081350e-01,
        9.92154979e-02, 1.76681257e-02, 7.87193136e-16, 3.20641142e-16,
        2.27704195e-16, 2.18355306e-16, 2.08494992e-16, 2.02486325e-16,
        1.87721369e-16, 1.77971609e-16, 1.63291154e-16, 1.57919245e-16,
        1.474

In [15]:
A = construct_matrix(m=1000000, n=100, singular_values=\
np.sort(np.random.rand(10))[::-1])
timeit(np.linalg.svd)(A, full_matrices = False) 

matrix has memory of  762.939453125 megabytes
execution time: 3.2619497776031494 seconds


(array([[ 6.48653959e-04, -1.75324399e-03,  4.74144555e-04, ...,
          7.86937638e-04, -1.15174762e-03,  2.92612260e-05],
        [ 3.56496221e-05, -2.49800269e-03,  1.18049001e-03, ...,
         -1.16554741e-04, -3.87663709e-03, -2.10969584e-03],
        [ 1.05964831e-03,  8.35484161e-04, -8.67222352e-05, ...,
          5.28228893e-04,  7.47092027e-03,  6.10840318e-04],
        ...,
        [ 1.65237066e-03,  1.10218495e-03,  3.81062630e-04, ...,
          1.45220246e-04, -2.29800010e-05,  4.53253164e-04],
        [ 1.28568595e-03,  4.67104286e-04,  9.23145158e-04, ...,
         -1.08387542e-03, -7.07702849e-04,  7.48992517e-04],
        [ 5.16260333e-04, -7.13236975e-04,  1.88316413e-03, ...,
          1.07905202e-03, -5.79608825e-04, -4.87583296e-05]]),
 array([6.22146144e-01, 6.12202996e-01, 5.69124307e-01, 5.55397504e-01,
        5.02193941e-01, 4.63429122e-01, 3.28661880e-01, 1.34318561e-01,
        1.14750647e-01, 1.67463163e-02, 5.28341167e-16, 5.19022568e-16,
        4.610

In [16]:
A = construct_matrix(m=10000000, n=10, singular_values=\
np.sort(np.random.rand(10))[::-1])
timeit(np.linalg.svd)(A, full_matrices = False) 

matrix has memory of  762.939453125 megabytes
execution time: 2.515782356262207 seconds


(array([[ 2.05130347e-04,  5.54736994e-04,  1.50257892e-04, ...,
         -4.66160787e-04,  1.38367871e-04,  2.35727353e-04],
        [ 1.12738375e-05,  7.90525654e-04,  3.73744449e-04, ...,
         -1.60390107e-04,  4.55998409e-05, -1.05316478e-04],
        [ 3.35103211e-04, -2.64571761e-04, -2.72555514e-05, ...,
         -1.28783375e-04,  1.95782111e-04, -3.93419431e-04],
        ...,
        [ 4.05170477e-04,  1.05841167e-04,  1.72153499e-04, ...,
          7.31529895e-05, -1.77962966e-04,  2.43149678e-04],
        [ 3.63816534e-04, -3.34049001e-04,  3.81618759e-04, ...,
         -4.59899483e-04,  5.23416006e-04,  4.42760383e-04],
        [ 5.10712209e-04,  2.39847827e-05, -5.30822872e-04, ...,
          5.02509122e-05,  1.79139008e-04, -8.76870865e-05]]),
 array([0.84401209, 0.81346803, 0.79863382, 0.67093568, 0.58909835,
        0.50725286, 0.48937041, 0.48543854, 0.33636518, 0.20282408]),
 array([[ 0.14045789,  0.32451897,  0.18745477,  0.46313348,  0.30089907,
          0.12310

In [21]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000, 10000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 68.42594361305237 seconds
relative error is:  0.0012929478409621376
np.allclose is:  False


In [23]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  48
execution time: 31.247755765914917 seconds
relative error is:  0.0036741015349595917
np.allclose is:  False


In [24]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 2000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 188.78008604049683 seconds
relative error is:  0.0012929477998570786
np.allclose is:  False


In [25]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 5000, 1000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 37.271209478378296 seconds
relative error is:  0.0012929468270844765
np.allclose is:  False


In [26]:
A = construct_matrix(m=10000, n=10000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 5000, 2000, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  762.939453125 megabytes
rank of matrix approximation is:  49
execution time: 56.88597249984741 seconds
relative error is:  0.0012929468269652993
np.allclose is:  False


In [2]:
A = construct_matrix(m=1000000, n=1000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 1000000, 100, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  7629.39453125 megabytes


MemoryError: Unable to allocate 7.28 TiB for an array with shape (1000000, 1000000) and data type float64

In [4]:
A = construct_matrix(m=1000000, n=1000, singular_values=\
np.sort(np.random.rand(50))[::-1])
U_aprx, S_aprx, V_aprx = blockSVD(A, 10000, 100, gamma=0.01)
quality(A, U_aprx, S_aprx, V_aprx) 

matrix has memory of  7629.39453125 megabytes
rank of matrix approximation is:  50
execution time: 1019.7014849185944 seconds


MemoryError: Unable to allocate 7.45 GiB for an array with shape (1000000, 1000) and data type float64